import gradio as gr
import asyncio
from app.services.workflow_service import SystematicReviewWorkflow

class PaperReviewUI:
    def __init__(self):
        self.workflow = SystematicReviewWorkflow()
    
    def _format_abstract(self, abstract_text: str, quality_score) -> str:
        """Format abstract with proper paragraphs and quality score"""
        if not abstract_text or abstract_text.startswith("No abstract"):
            return "## 📝 Abstract\n\nNo abstract generated. Please check your API key or try again."
        
        # Ensure proper paragraph breaks
        paragraphs = abstract_text.split('\n\n')
        formatted_paragraphs = []
        
        for para in paragraphs:
            para = para.strip()
            if para:
                # Ensure paragraphs end with proper punctuation
                if not para.endswith(('.', '?', '!')):
                    para += '.'
                formatted_paragraphs.append(para)
        
        # If no paragraph breaks, try to create them
        if len(formatted_paragraphs) <= 1 and len(abstract_text) > 300:
            sentences = abstract_text.split('. ')
            if len(sentences) > 4:
                para_size = max(2, len(sentences) // 3)
                new_paragraphs = []
                for i in range(0, len(sentences), para_size):
                    para = '. '.join(sentences[i:i+para_size])
                    if para:
                        if not para.endswith('.'):
                            para += '.'
                        new_paragraphs.append(para)
                formatted_paragraphs = new_paragraphs
        
        abstract_body = '\n\n'.join(formatted_paragraphs)
        
        # Format quality score display
        score = quality_score if isinstance(quality_score, (int, float)) else 0
        score_display = f"{score:.1f}/10" if isinstance(score, (int, float)) else "N/A"
        
        return f"""## 📝 Abstract

{abstract_body}

---

## 📊 Quality Assessment

| Metric | Score |
|--------|-------|
| **Overall Quality** | **{score_display}** |

---

### 💡 Quality Feedback

*The review has been generated by AI. Please verify critical claims against original sources.*
"""
    
    def _format_methods(self, methods_text: str, key_themes: list) -> str:
        """Format methods comparison with better structure"""
        if not methods_text or methods_text.startswith("No methods"):
            return "## 🔬 Methods Comparison\n\nNo methods comparison generated."
        
        # Format themes as bullet points
        themes_section = ""
        if key_themes and len(key_themes) > 0:
            themes_list = '\n'.join([f"- {theme}" for theme in key_themes[:10]])
            themes_section = f"""

---

## 💡 Key Themes Identified

{themes_list}
"""
        
        return f"""## 🔬 Methods Comparison

{methods_text}
{themes_section}
"""
    
    def _format_results(self, results_text: str, revision_suggestions: list) -> str:
        """Format results synthesis with revision suggestions"""
        if not results_text or results_text.startswith("No results"):
            return "## 📈 Results Synthesis\n\nNo results synthesis generated."
        
        suggestions_section = ""
        if revision_suggestions and len(revision_suggestions) > 0:
            suggestions_list = '\n'.join([f"- {suggestion}" for suggestion in revision_suggestions[:5]])
            suggestions_section = f"""

---

## ⚠️ Revision Suggestions

{suggestions_list}

> 💡 **Tip:** Run the review again with different papers or adjust the topic for improved results.
"""
        
        return f"""## 📈 Results Synthesis

{results_text}
{suggestions_section}
"""
    
    def _format_references(self, references: list) -> str:
        """Format APA references with proper numbering"""
        if not references or len(references) == 0:
            return "## 📚 References\n\nNo references generated."
        
        formatted_refs = []
        for i, ref in enumerate(references, 1):
            formatted_refs.append(f"{i}. {ref}")
        
        references_body = '\n\n'.join(formatted_refs)
        
        return f"""## 📚 References (APA 7th Edition)

{references_body}

---
*Citations are auto-generated. Please verify against original sources.*
"""
    
    def _format_papers_analyzed(self, papers: list) -> str:
        """Format papers analyzed with better structure"""
        if not papers:
            return "## 📄 Papers Analyzed\n\nNo papers found for the given topic. Please try a different topic or check your search terms."
        
        papers_body = ""
        for i, paper in enumerate(papers, 1):
            cache_indicator = "✅ (from cache)" if paper.local_pdf_path else "📥 (newly downloaded)"
            authors_str = ', '.join(paper.authors[:3]) if paper.authors else 'N/A'
            if len(paper.authors) > 3:
                authors_str += f" et al. ({len(paper.authors) - 3} more)"
            
            papers_body += f"""
### {i}. {paper.title} {cache_indicator}

| Property | Details |
|----------|---------|
| **Authors** | {authors_str} |
| **Year** | {paper.year} |
| **Citations** | {paper.citation_count} |
| **Venue** | {paper.venue if paper.venue else 'N/A'} |

"""
        
        return f"""## 📄 Papers Analyzed

{papers_body}
"""
    
    async def run_review(self, topic: str, max_papers: int, year_from: int, year_to: int):
        """Run the systematic review workflow with cache option"""
        if not topic or topic.strip() == "":
            yield "Please enter a research topic", "", "", "", "", "", "❌ Error: No topic provided"
            return
        
        try:
            # Run workflow
            result = await self.workflow.run_workflow(topic, max_papers)
            
            # Get cache stats
            cache_stats = result.get('cache_stats', {})
            cache_info = f"📦 Cache: {cache_stats.get('total_cached_papers', 0)} papers | {cache_stats.get('cache_size_mb', 0)} MB"
            
            # Get quality score
            quality_score = result.get('quality_assessment', {}).get('quality_score', 0)
            
            # Format outputs using new formatters
            abstract = self._format_abstract(result.get('abstract', ''), quality_score)
            methods = self._format_methods(result.get('methods_section', ''), result.get('key_themes', []))
            results = self._format_results(result.get('results_section', ''), result.get('revision_suggestions', []))
            references = self._format_references(result.get('apa_references', []))
            papers_analyzed = self._format_papers_analyzed(result.get('papers', []))
            
            status = f"✅ Review completed! Stage: {result.get('current_stage', 'completed')}\n{cache_info}"
            if not result.get('papers'):
                status = f"⚠️ No papers found. Please try a different topic.\n{cache_info}"
            
            yield abstract, methods, results, references, papers_analyzed, cache_info, status
            
        except Exception as e:
            error_msg = f"❌ Error: {str(e)}"
            yield error_msg, error_msg, error_msg, error_msg, error_msg, "", error_msg
    
    def clear_cache(self):
        """Clear the download cache"""
        self.workflow.clear_cache()
        return "✅ Cache cleared successfully!", "📦 Cache: 0 papers | 0 MB"
    
    def get_cache_info(self):
        """Get current cache information"""
        stats = self.workflow.get_cache_stats()
        return f"📦 Cache contains {stats.get('total_cached_papers', 0)} papers ({stats.get('cache_size_mb', 0)} MB)"
    
    def create_interface(self):
        """Create Gradio interface"""
        with gr.Blocks(title="AI Systematic Review Generator", theme=gr.themes.Soft(), css="""
            .gradio-container {
                max-width: 1200px !important;
                margin: auto !important;
            }
            h1 {
                text-align: center;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
                padding: 20px;
            }
            .cache-status {
                background: #f0f9ff;
                border-left: 4px solid #3b82f6;
                padding: 10px;
                border-radius: 5px;
            }
            table {
                width: 100%;
                border-collapse: collapse;
                margin: 16px 0;
            }
            th, td {
                padding: 8px 12px;
                border: 1px solid #e2e8f0;
                text-align: left;
            }
            th {
                background-color: #f1f5f9;
                font-weight: 600;
            }
        """) as demo:
            gr.Markdown("""
            # 📚 AI-Powered Systematic Review Generator
            ### Automatically search, analyze, and synthesize research papers using AI
            """)
            
            with gr.Row():
                with gr.Column(scale=2):
                    topic_input = gr.Textbox(
                        label="🔍 Research Topic",
                        placeholder="e.g., 'Machine Learning for Healthcare', 'Climate Change Impact on Agriculture', 'Deep Learning in Computer Vision'",
                        lines=2
                    )
                    
                    with gr.Row():
                        max_papers = gr.Slider(
                            minimum=1, maximum=10, value=3, step=1,
                            label="Number of Papers to Analyze"
                        )
                        year_from = gr.Number(label="Year From", value=2020, precision=0)
                        year_to = gr.Number(label="Year To", value=2024, precision=0)
                    
                    with gr.Row():
                        submit_btn = gr.Button("🚀 Generate Systematic Review", variant="primary", size="lg")
                        clear_btn = gr.Button("🗑️ Clear All", variant="secondary", size="lg")
                
                with gr.Column(scale=1):
                    cache_status = gr.Textbox(label="💾 Cache Status", interactive=False, lines=1)
                    refresh_cache_btn = gr.Button("🔄 Refresh Cache Info", size="sm")
                    clear_cache_btn = gr.Button("🗑️ Clear Cache", variant="stop", size="sm")
                    status_text = gr.Textbox(label="📊 Status", interactive=False, lines=3)
            
            with gr.Tabs():
                with gr.TabItem("📝 Abstract & Quality"):
                    abstract_output = gr.Markdown()
                
                with gr.TabItem("🔬 Methods & Themes"):
                    methods_output = gr.Markdown()
                
                with gr.TabItem("📈 Results & Revisions"):
                    results_output = gr.Markdown()
                
                with gr.TabItem("📚 References"):
                    references_output = gr.Markdown()
                
                with gr.TabItem("📄 Papers Analyzed"):
                    papers_output = gr.Markdown()
            
            # Example queries
            gr.Markdown("### 🔍 Quick Examples")
            with gr.Row():
                gr.Button("🤖 Machine Learning in Healthcare").click(
                    fn=lambda: "Machine Learning in Healthcare", 
                    outputs=topic_input
                )
                gr.Button("🌍 Climate Change Policy").click(
                    fn=lambda: "Climate Change Policy", 
                    outputs=topic_input
                )
                gr.Button("💻 Quantum Computing").click(
                    fn=lambda: "Quantum Computing Applications", 
                    outputs=topic_input
                )
                gr.Button("🧬 CRISPR Gene Editing").click(
                    fn=lambda: "CRISPR Gene Editing", 
                    outputs=topic_input
                )
                gr.Button("🤝 Remote Work Productivity").click(
                    fn=lambda: "Remote Work Productivity", 
                    outputs=topic_input
                )
            
            # Event handlers
            submit_btn.click(
                fn=self.run_review,
                inputs=[topic_input, max_papers, year_from, year_to],
                outputs=[abstract_output, methods_output, results_output, references_output, papers_output, cache_status, status_text]
            )
            
            clear_btn.click(
                fn=lambda: ["", "", "", "", "", "", ""],
                outputs=[topic_input, abstract_output, methods_output, results_output, references_output, cache_status, status_text]
            )
            
            refresh_cache_btn.click(
                fn=self.get_cache_info,
                outputs=[cache_status]
            )
            
            clear_cache_btn.click(
                fn=self.clear_cache,
                outputs=[status_text, cache_status]
            )
            
            # Load initial cache info
            demo.load(fn=self.get_cache_info, outputs=[cache_status])
        
        return demo

def launch_ui():
    ui = PaperReviewUI()
    demo = ui.create_interface()
    demo.launch(server_name="0.0.0.0", server_port=7860, share=False)

if __name__ == "__main__":
    launch_ui()